const singleAlbumTypes = {
  LOAD_SINGLE_ALBUM: 'LOAD_SINGLE_ALBUM',
  LOAD_SINGLE_ALBUM_SUCCESS: 'LOAD_SINGLE_ALBUM_SUCCESS',
  LOAD_SINGLE_ALBUM_ERROR: 'LOAD_SINGLE_ALBUM_ERROR',
};

export default singleAlbumTypes;
