const trackPlaylistTypes = {
  LOAD_TRACK_PLAYLIST: 'LOAD_TRACK_PLAYLIST',
  LOAD_TRACK_PLAYLIST_SUCCESS: 'LOAD_TRACK_PLAYLIST_SUCCESS',
  LOAD_TRACK_PLAYLIST_ERROR: 'LOAD_TRACK_PLAYLIST_ERROR',
};

export default trackPlaylistTypes;
