const chartPlaylistTypes = {
  LOAD_CHART_PLAYLIST: 'LOAD_CHART_PLAYLIST',
  LOAD_CHART_PLAYLIST_SUCCESS: 'LOAD_CHART_PLAYLIST_SUCCESS',
  LOAD_CHART_PLAYLIST_ERROR: 'LOAD_CHART_PLAYLIST_ERROR',
};

export default chartPlaylistTypes;
