const singleRadioTypes = {
  LOAD_SINGLE_RADIO: 'LOAD_SINGLE_RADIO',
  LOAD_SINGLE_RADIO_SUCCESS: 'LOAD_SINGLE_RADIO_SUCCESS',
  LOAD_SINGLE_RADIO_ERROR: 'LOAD_SINGLE_RADIO_ERROR',
};

export default singleRadioTypes;
