const searchTrackTypes = {
  LOAD_SEARCH_TRACK: 'LOAD_SEARCH_TRACK',
  LOAD_SEARCH_TRACK_SUCCESS: 'LOAD_SEARCH_TRACK_SUCCESS',
  LOAD_SEARCH_TRACK_ERROR: 'LOAD_SEARCH_TRACK_ERROR',
};

export default searchTrackTypes;
