const searchAlbumTypes = {
  LOAD_SEARCH_ALBUM: 'LOAD_SEARCH_ALBUM',
  LOAD_SEARCH_ALBUM_SUCCESS: 'LOAD_SEARCH_ALBUM_SUCCESS',
  LOAD_SEARCH_ALBUM_ERROR: 'LOAD_SEARCH_ALBUM_ERROR',
};

export default searchAlbumTypes;
