const searchArtistTypes = {
  LOAD_SEARCH_ARTIST: 'LOAD_SEARCH_ARTIST',
  LOAD_SEARCH_ARTIST_SUCCESS: 'LOAD_SEARCH_ARTIST_SUCCESS',
  LOAD_SEARCH_ARTIST_ERROR: 'LOAD_SEARCH_ARTIST_ERROR',
};

export default searchArtistTypes;
